#!/usr/bin/env python

import os
import os.path
import sys
import subprocess

vars = {}
args = sys.argv[1:]
for arg in args[:]:
    if arg.startswith("-D"):
        key, value = arg.lstrip("-D").split("=", 1)
        vars[key] = os.path.realpath(os.path.expanduser(value))
        args.pop(0)
    else:
        break

src = args[0]
dst = args[1]

logfile = open("/tmp/copyTemplate.log", "w")
logfile.write("""
src = %s
dst = %s
vars = %s
""" % (src, dst, vars))

# copy directory
subprocess.Popen(["/usr/bin/rsync", "-a", src, dst]).wait()

def replaceVars(s, vars):
    global logfile
    for k, v in vars.iteritems():
        logfile.write("replace %s with %s\n" % (k, v))
        s = s.replace("@@%s@@" % k, v)
    return s

def walk_replaceVars(arg, dirname, fileNames):
    for file in fileNames:
        if file.endswith(".in"):
            outfileName = file.rstrip(".in")
            outfile = open(os.path.join(dirname, outfileName), "w")
            infilePath = os.path.join(dirname, file)
            s = replaceVars(open(infilePath).read(), vars)
            outfile.write(s)
            os.unlink(infilePath)

os.path.walk(dst, walk_replaceVars, None)
