#! /usr/bin/env python

import os
import errno
import sys
import subprocess

dst = sys.argv[1]

libraryPath = os.path.join(dst, "lib/arc")
try:
	os.mkdir(libraryPath)
except OSError, error:
	if error.errno == errno.EEXIST:
		pass
	else:
		raise

xcodeToolChainPath = "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain"
srcLibPath = os.path.join(xcodeToolChainPath, "usr/lib/arc/")

files = [
    "libarclite_iphoneos.a",
    "libarclite_iphonesimulator.a",
    "libarclite_macosx.a",
]

for file in files:
	subprocess.Popen(["/bin/cp", os.path.join(srcLibPath, file), libraryPath])
